import React,{useState} from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { PageTransition } from '../components/layout/PageTransition';
import { Button } from '../components/common/Button';
import { authService } from '../services/authService';
import logoImg from '../assets/branding/barely-junk-logo.png';

export const ResetPassword:React.FC=()=>{
  const [params]=useSearchParams();const token=params.get('token')||'';const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const [done,setDone]=useState(false);const [busy,setBusy]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match.');return;}setBusy(true);try{await authService.resetPassword(token,password);setDone(true);}catch(err){setError(err instanceof Error?err.message:'Could not reset your password. Request a new link.');}finally{setBusy(false);}};
  return <PageTransition><div className="py-16 bg-paper min-h-screen flex items-center justify-center px-4"><div className="w-full max-w-md bg-white border-4 border-brand-black p-8 shadow-brutal-lg space-y-6"><div className="text-center space-y-3"><img src={logoImg} alt="BARELY JUNK" className="h-16 mx-auto"/><h1 className="font-display font-black text-3xl uppercase">RESET PASSWORD</h1><p className="font-mono text-xs text-gray-600">Choose a new password with at least 8 characters.</p></div>{done?<div role="status" className="text-center space-y-4"><p className="text-emerald-800 font-bold">Password updated. You can now log in.</p><Link to="/login" className="inline-block"><Button variant="accent">GO TO LOGIN</Button></Link></div>:!token?<p role="alert" className="text-red-700 font-bold">This reset link is missing its token. Request a new link.</p>:<form onSubmit={submit} className="space-y-4 font-mono text-xs">{error&&<p role="alert" className="text-red-700 font-bold">{error}</p>}<label className="font-bold block">NEW PASSWORD<input type="password" required minLength={8} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full p-3 border-2 border-brand-black font-sans text-sm"/></label><label className="font-bold block">CONFIRM PASSWORD<input type="password" required minLength={8} maxLength={128} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1 w-full p-3 border-2 border-brand-black font-sans text-sm"/></label><Button type="submit" variant="accent" size="lg" isFullWidth disabled={busy}>{busy?'UPDATING…':'UPDATE PASSWORD'}</Button></form>}<div className="text-center font-mono text-xs"><Link to="/login" className="font-bold text-brand-orange hover:underline">BACK TO LOGIN</Link></div></div></div></PageTransition>;
};
